from sqlalchemy import create_engine, Column, Integer, String
from sqlalchemy.engine import URL
from sqlalchemy.orm import declarative_base, sessionmaker
from decouple import config

# Database configuration
DATABASE_URL = URL.create(
    drivername="postgresql",
    username=config("DB_USER"),
    password=config("DB_PASSWORD"),
    host=config("DB_HOST", default="localhost"),
    database=config("DB_NAME", default="whatsapp_ai_chatbot"),
    port=config("DB_PORT", default=5432),
)

# Creating engine and session
engine = create_engine(DATABASE_URL)
SessionLocal = sessionmaker(bind=engine)
Base = declarative_base()


class Conversation(Base):
    """
    ORM model for the conversations table.

    Attributes:
    - id: Unique identifier for each conversation.
    - sender: WhatsApp number of the sender.
    - message: Message sent by the sender.
    - response: Response generated by the bot.
    """

    __tablename__ = "conversations"

    id = Column(Integer, primary_key=True, index=True)
    sender = Column(String)
    message = Column(String)
    response = Column(String)


# Create the table if it doesn't exist
Base.metadata.create_all(engine)
